USE master
GO
ALTER DATABASE ClinicPooya SET RECOVERY SIMPLE WITH ROLLBACK IMMEDIATE
GO
USE ClinicPooya
GO
SP_HELPFILE
GO
DBCC SHRINKFILE(ClinicPooya_log,1)
GO
CHECKPOINT
GO
SP_HELPFILE
GO
GO
ALTER DATABASE ClinicPooya 
	MODIFY FILE ( NAME = N'ClinicPooya_log', SIZE = 2GB , FILEGROWTH = 1024MB )
GO
ALTER DATABASE ClinicPooya SET RECOVERY FULL
GO
